# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x0cimageservice\"<\n\x12ImageUploadRequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"(\n\x13ImageUploadResponse\x12\x11\n\timage_url\x18\x01 \x01(\t2b\n\x0cImageService\x12R\n\x0bUploadImage\x12 .imageservice.ImageUploadRequest\x1a!.imageservice.ImageUploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=29
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=89
  _globals['_IMAGEUPLOADRESPONSE']._serialized_start=91
  _globals['_IMAGEUPLOADRESPONSE']._serialized_end=131
  _globals['_IMAGESERVICE']._serialized_start=133
  _globals['_IMAGESERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
